on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'ID of the PR to comment'
        required: true
        type: integer
      success:
        description: 'Is the workflow successful?'
        required: true
        type: boolean
      dashboard_page:
        description: 'URL to the dashboard page'
        required: true
        type: string

permissions:
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.inputs.pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Success: ${context.inputs.success} [here](${context.inputs.dashboard_page}).`
            })
