on:
  pull_request:
    types: opened

permissions:
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Hello! There is an additional workflow running for your PR.
          It will be available [here](https://riscv-ci.pages.thales-invia.fr/dashboard/dashboard_core-v-verif_github-pr..${{ github.event.pull_request.number }}..head.html) later.
